In [1]:
import torch

In [2]:
from modules import train_models, final_models, dataset, params


In [3]:
train_model = train_models.TrainModel(final_models.LineRecognition, dataset.OCRDataset, params.params, params.params)

In [4]:
train_model.fit(0.0001, 2)

Iteration 0 of epoch 0) loss: inf
Iteration 1 of epoch 0) loss: nan
Iteration 2 of epoch 0) loss: nan
Iteration 3 of epoch 0) loss: nan
Iteration 4 of epoch 0) loss: nan
Iteration 5 of epoch 0) loss: nan
Iteration 6 of epoch 0) loss: nan
Iteration 7 of epoch 0) loss: nan
Iteration 8 of epoch 0) loss: nan
Iteration 9 of epoch 0) loss: nan
Iteration 10 of epoch 0) loss: nan
Iteration 11 of epoch 0) loss: nan
Iteration 12 of epoch 0) loss: nan
Iteration 13 of epoch 0) loss: nan
Iteration 14 of epoch 0) loss: nan
Iteration 15 of epoch 0) loss: nan
Iteration 16 of epoch 0) loss: nan
Iteration 17 of epoch 0) loss: nan
Iteration 18 of epoch 0) loss: nan
Iteration 19 of epoch 0) loss: nan
Iteration 20 of epoch 0) loss: nan
Iteration 21 of epoch 0) loss: nan
Iteration 22 of epoch 0) loss: nan
Iteration 23 of epoch 0) loss: nan
Iteration 24 of epoch 0) loss: nan
Iteration 25 of epoch 0) loss: nan
Iteration 26 of epoch 0) loss: nan
Iteration 27 of epoch 0) loss: nan
Iteration 28 of epoch 0) loss:

In [5]:
ctc_loss = torch.nn.CTCLoss()
target_lengths = [30, 25, 20]
input_lengths = [50, 50, 50]
targets = torch.randint(1, 15, (sum(target_lengths),), dtype=torch.int)
log_probs = torch.randn(50, 3, 15, dtype=torch.float).log_softmax(2)
res = ctc_loss(log_probs, targets, input_lengths, target_lengths)

output = torch.randn(3,200,2000)
target_length = [6]
target = ["hello"]
out_length = [2000]

res = ctc_loss(output, target, out_length, target_length)

TypeError: ctc_loss() received an invalid combination of arguments - got (Tensor, list, list, list, int, int, bool), but expected one of:
 * (Tensor log_probs, Tensor targets, tuple of ints input_lengths, tuple of ints target_lengths, int blank, int reduction, bool zero_infinity)
      didn't match because some of the arguments have invalid types: (Tensor, !list!, !list!, !list!, int, int, bool)
 * (Tensor log_probs, Tensor targets, Tensor input_lengths, Tensor target_lengths, int blank, int reduction, bool zero_infinity)
      didn't match because some of the arguments have invalid types: (Tensor, !list!, !list!, !list!, int, int, bool)


In [1]:
from modules.dataset import OCRDataset, dataloader_collate_fn
from torch.utils.data import DataLoader
from modules import params

dataset = OCRDataset(params.params)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True, collate_fn=dataloader_collate_fn)

In [1]:
import torch

In [2]:
import torch
a = torch.tensor([
[[1,2,3], [1,2,3]]
,[[4,5,6], [5,6,2]]
, [[7,8,9], [7,5,9]]
, [[7,8,9], [7,5,9]]
], dtype=torch.float32)
a.sum()

tensor(130.)

In [3]:
from torchvision.transforms import Normalize
b = Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
b(a)

tensor([[[ 1.,  3.,  5.]],

        [[ 7.,  9., 11.]],

        [[13., 15., 17.]]])

In [6]:
from torchvision.transforms.functional import resize

In [1]:
import numpy as np
np.float32([10,20])

array([10., 20.], dtype=float32)

In [3]:
torch.tensor([990000000], dtype=torch.float32)

tensor([9.9000e+08])